version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ../.deployment/backend.Dockerfile
    ports:
      - "8000:80"
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ../.deployment/frontend.Dockerfile
      args:
        VITE_ENVIRONMENT: production
        VITE_API_URL: http://summai-challenge.api.ghassen-jebbari.de:8000
    ports:
      - "3000:3000"
    restart: always
